animals:
- - animals
  - dog.yaml
- - animals
  - sheep.yaml
- - animals
  - cat.yaml
- - animals
  - bird.yaml
- - animals
  - cow.yaml
- - animals
  - crab.yaml
- - animals
  - fish.yaml
- - animals
  - fox.yaml
- - animals
  - snake.yaml
- - animals
  - spider.yaml
- - animals
  - squirrel.yaml
- - animals
  - goat.yaml
- - animals
  - mouse.yaml
- - animals
  - lizzard.yaml
- - animals
  - tiger.yaml
- - animals
  - monkey.yaml
- - animals
  - bat.yaml
- - animals
  - lion.yaml
- - animals
  - elephant.yaml
- - animals
  - crocodile.yaml
- - animals
  - horse.yaml
- - animals
  - zebra.yaml
- - animals
  - fly.yaml
- - animals
  - bear.yaml
- - animals
  - shark.yaml
- - animals
  - jellyfish.yaml
- - animals
  - hippo.yaml
- - animals
  - panda.yaml
- - animals
  - frog.yaml
- - animals
  - giraffe.yaml
- - animals
  - rabbit.yaml
- - animals
  - snail.yaml
confidence_for_certain: 0.95
discard_propability: 0.05
guess:
- questions
- guess.yaml
max_questions: 20
menu:
- topics
- game_menu.top
panic_questions: 3
questions:
- - questions
  - leash.yaml
- - questions
  - live_in_house.yaml
- - questions
  - legs.yaml
- - questions
  - fly.yaml
- - questions
  - fur.yaml
- - questions
  - scales.yaml
- - questions
  - bigger_than_horse.yaml
- - questions
  - eggs_or_babies.yaml
- - questions
  - carnivore.yaml
- - questions
  - hard_body.yaml
- - questions
  - region_of_living.yaml
- - questions
  - number_of_legs.yaml
- - questions
  - tail.yaml
- - questions
  - horns.yaml
- - questions
  - stripes.yaml
- - questions
  - bigger_than_this.yaml
- - questions
  - swim.yaml
